-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-03-25 09:17:50 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE tbl_albumes (
    id_album           INTEGER NOT NULL,
    nombre_album       VARCHAR2(50),
    portada            VARCHAR2(300),
    duracion           INTEGER,
    fecha_lanzamiento  DATE,
    cantidad_canciones INTEGER,
    id_usuario         INTEGER NOT NULL
);

ALTER TABLE tbl_albumes ADD CONSTRAINT tbl_albumes_pk PRIMARY KEY ( id_album );

CREATE TABLE tbl_artistas (
    id_usuario        INTEGER NOT NULL,
    id_merch          INTEGER NOT NULL,
    oyentes_mensuales INTEGER,
    biografia         varchar(4000)
);

ALTER TABLE tbl_artistas ADD CONSTRAINT tbl_artistas_pk PRIMARY KEY ( id_usuario );

CREATE TABLE tbl_canciones (
    id_media              INTEGER NOT NULL,
    letra_cancion         varchar(4000),
    id_album              INTEGER NOT NULL,
    id_genero_musical     INTEGER NOT NULL,
    id_creditos_musicales INTEGER NOT NULL,
    id_usuario            INTEGER NOT NULL,
    id_idioma             INTEGER NOT NULL
);

CREATE UNIQUE INDEX tbl_canciones__idx ON
    tbl_canciones (
        id_creditos_musicales
    ASC );

ALTER TABLE tbl_canciones ADD CONSTRAINT tbl_canciones_pk PRIMARY KEY ( id_media );

CREATE TABLE tbl_canciones_artistas (
    id_usuario INTEGER NOT NULL,
    id_media   INTEGER NOT NULL
);

ALTER TABLE tbl_canciones_artistas ADD CONSTRAINT tbl_canciones_artistas_pk PRIMARY KEY ( id_usuario,
                                                                                          id_media );

CREATE TABLE tbl_creditos (
    id_creditos_musicales INTEGER NOT NULL,
    firma_discografica    VARCHAR2(100),
    id_artista            INTEGER NOT NULL,
    id_productor          INTEGER NOT NULL
);

ALTER TABLE tbl_creditos ADD CONSTRAINT tbl_creditos_pk PRIMARY KEY ( id_creditos_musicales );

CREATE TABLE tbl_episodio (
    descripcion_episodio varchar(4000),
    id_media             INTEGER NOT NULL,
    id_podcast           INTEGER NOT NULL
);

ALTER TABLE tbl_episodio ADD CONSTRAINT tbl_episodio_pk PRIMARY KEY ( id_media );

CREATE TABLE tbl_escritores (
    id_escritor    INTEGER NOT NULL,
    primer_nombre  VARCHAR2(500),
    segundo_nombre VARCHAR2(500),
    apellido       VARCHAR2(500)
);

ALTER TABLE tbl_escritores ADD CONSTRAINT tbl_escritores_pk PRIMARY KEY ( id_escritor );

CREATE TABLE tbl_eventos (
    id_evento     INTEGER NOT NULL,
    id_usuario    INTEGER NOT NULL,
    id_lugar      INTEGER NOT NULL,
    nombre_evento VARCHAR2(500),
    fecha_evento  DATE,
    url_tickets   varchar(4000)
);

ALTER TABLE tbl_eventos ADD CONSTRAINT tbl_eventos_pk PRIMARY KEY ( id_evento );

CREATE TABLE tbl_facturas (
    id_factura    INTEGER NOT NULL,
    id_usuario    INTEGER NOT NULL,
    id_plan       INTEGER NOT NULL,
    fecha_cobro   DATE,
    monto_cobrado FLOAT
);

ALTER TABLE tbl_facturas ADD CONSTRAINT tbl_historico_facturas_pk PRIMARY KEY ( id_factura );

CREATE TABLE tbl_genero (
    id_genero     INTEGER NOT NULL,
    nombre_genero VARCHAR2(100)
);

ALTER TABLE tbl_genero ADD CONSTRAINT tbl_genero_pk PRIMARY KEY ( id_genero );

CREATE TABLE tbl_generos_musicales (
    id_genero_musical     INTEGER NOT NULL,
    nombre_genero_musical VARCHAR2(500)
);

ALTER TABLE tbl_generos_musicales ADD CONSTRAINT tbl_generos_musicales_pk PRIMARY KEY ( id_genero_musical );

CREATE TABLE tbl_historial_canciones (
    id_historial_de_reproduccion INTEGER NOT NULL,
    id_media                     INTEGER NOT NULL,
    fecha_reproduccion           DATE
);

CREATE TABLE tbl_historial_reproduccion (
    id_historial_repr INTEGER NOT NULL
);

ALTER TABLE tbl_historial_reproduccion ADD CONSTRAINT tbl_historial_repr_pk PRIMARY KEY ( id_historial_repr );

CREATE TABLE tbl_idiomas (
    id_idioma     INTEGER NOT NULL,
    nombre_idioma VARCHAR2(500)
);

ALTER TABLE tbl_idiomas ADD CONSTRAINT tbl_idiomas_pk PRIMARY KEY ( id_idioma );

CREATE TABLE tbl_listas_reproduccion (
    id_lista_reproduccion       INTEGER NOT NULL,
    id_usuario_propietario      INTEGER NOT NULL,
    nombre_lista_reproduccion   VARCHAR2(100),
    cantidad_canciones          INTEGER,
    duracion_lista_reproduccion INTEGER
);

ALTER TABLE tbl_listas_reproduccion ADD CONSTRAINT tbl_listas_reproduccion_pk PRIMARY KEY ( id_lista_reproduccion );

CREATE TABLE tbl_listas_seguidas (
    id_lista_seguidas     INTEGER NOT NULL,
    fecha_seguimiento     DATE,
    id_usuario            INTEGER NOT NULL,
    id_rol                INTEGER NOT NULL,
    id_lista_reproduccion INTEGER NOT NULL
);

ALTER TABLE tbl_listas_seguidas ADD CONSTRAINT tbl_listas_seguidas_pk PRIMARY KEY ( id_lista_seguidas );

CREATE TABLE tbl_lugares (
    id_lugar     INTEGER NOT NULL,
    nombre_lugar VARCHAR2(100),
    latitud      NUMBER,
    longitud     NUMBER,
    id_pais      INTEGER NOT NULL
);

ALTER TABLE tbl_lugares ADD CONSTRAINT tbl_lugares_pk PRIMARY KEY ( id_lugar );

CREATE TABLE tbl_media (
    id_media             INTEGER NOT NULL,
    nombre_media         VARCHAR2(200),
    duracion_media       INTEGER,
    reproducciones_media INTEGER,
    fecha_publicacion    DATE
);

ALTER TABLE tbl_media ADD CONSTRAINT tbl_media_pk PRIMARY KEY ( id_media );

CREATE TABLE tbl_merch (
    id_merch         INTEGER NOT NULL,
    id_talla         INTEGER NOT NULL,
    nombre_merch     VARCHAR2(500),
    decripcion_merch varchar(4000),
    precio_merch     NUMBER,
    stock_merch      INTEGER NOT NULL
);

ALTER TABLE tbl_merch ADD CONSTRAINT tbl_merch_pk PRIMARY KEY ( id_merch );

CREATE TABLE tbl_pago_planes (
    id_plan_pagado      INTEGER NOT NULL,
    fecha_inicio_plan   DATE,
    fecha_fin_plan      DATE,
    id_usuario          INTEGER NOT NULL,
    id_plan             INTEGER NOT NULL,
    referencia_bancaria VARCHAR2(500)
);

CREATE UNIQUE INDEX tbl_pago_planes__idx ON
    tbl_pago_planes (
        id_usuario
    ASC );

ALTER TABLE tbl_pago_planes ADD CONSTRAINT tbl_pago_planes_pk PRIMARY KEY ( id_plan_pagado );

CREATE TABLE tbl_paises (
    id_pais          INTEGER NOT NULL,
    nombre_pais      VARCHAR2(1000),
    abreviacion_pais VARCHAR2(10),
    icono_pais       varchar(4000),
    id_idioma        INTEGER NOT NULL
);

ALTER TABLE tbl_paises ADD CONSTRAINT tbl_paises_pk PRIMARY KEY ( id_pais );

CREATE TABLE tbl_planes (
    id_plan            INTEGER NOT NULL,
    nombre_plan        VARCHAR2(100),
    precio             NUMBER,
    usuarios_admitidos INTEGER,
    duracion_plan      INTEGER
);

ALTER TABLE tbl_planes ADD CONSTRAINT tbl_planes_pk PRIMARY KEY ( id_plan );

CREATE TABLE tbl_podcasters (
    id_usuario            INTEGER NOT NULL,
    "Cantidad de podcast" INTEGER,
    id_podcast            INTEGER NOT NULL
);

ALTER TABLE tbl_podcasters ADD CONSTRAINT tbl_podcasters_pk PRIMARY KEY ( id_usuario );

CREATE TABLE tbl_podcasts (
    id_podcast          INTEGER NOT NULL,
    id_idioma           INTEGER NOT NULL,
    nombre_podcast      VARCHAR2(300),
    url_portada_podcast VARCHAR2(300),
    descripcion_podcast varchar(4000),
    id_usuario          INTEGER NOT NULL
);

ALTER TABLE tbl_podcasts ADD CONSTRAINT podcasts_pk PRIMARY KEY ( id_podcast );

CREATE TABLE tbl_productores (
    id_productor   INTEGER NOT NULL,
    primer_nombre  VARCHAR2(500),
    segundo_nombre VARCHAR2(500),
    apellido       VARCHAR2(500)
);

ALTER TABLE tbl_productores ADD CONSTRAINT tbl_escritoresv1_pk PRIMARY KEY ( id_productor );

CREATE TABLE tbl_rol_lista_r (
    id_rol     INTEGER NOT NULL,
    nombre_rol VARCHAR2(100)
);

ALTER TABLE tbl_rol_lista_r ADD CONSTRAINT tbl_rol_lista_r_pk PRIMARY KEY ( id_rol );

CREATE TABLE tbl_tallas (
    id_talla     INTEGER NOT NULL,
    nombre_talla VARCHAR2(10)
);

ALTER TABLE tbl_tallas ADD CONSTRAINT tbl_tallas_pk PRIMARY KEY ( id_talla );

CREATE TABLE tbl_tipo_redes_sociales (
    id_red_social     INTEGER NOT NULL,
    nombre_red_social VARCHAR2(500),
    icono_red_social  varchar(4000)
);

ALTER TABLE tbl_tipo_redes_sociales ADD CONSTRAINT reder_sociales_pk PRIMARY KEY ( id_red_social );

CREATE TABLE tbl_usuario_estandar (
    id_usuario                   INTEGER NOT NULL,
    id_plan_pagado               INTEGER NOT NULL,
    id_historial_de_reproduccion INTEGER NOT NULL,
    id_plan                      INTEGER NOT NULL
);

CREATE UNIQUE INDEX tbl_usuario_estandar__idx ON
    tbl_usuario_estandar (
        id_historial_de_reproduccion
    ASC,
        id_plan_pagado
    ASC );

ALTER TABLE tbl_usuario_estandar ADD CONSTRAINT tbl_usuario_estandar_pk PRIMARY KEY ( id_usuario );

CREATE TABLE tbl_usuario_red_social (
    id_red_social INTEGER NOT NULL,
    id_usuario    INTEGER NOT NULL,
    user_name     INTEGER
);

CREATE TABLE tbl_usuarios (
    id_usuario       INTEGER NOT NULL,
    id_genero        INTEGER NOT NULL,
    correo           VARCHAR2(100) NOT NULL,
    nombre_usuario   VARCHAR2(150) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    fecha_registro   DATE,
    genero           VARCHAR2(100),
    url_foto_perfil  VARCHAR2(150),
    contrase�a       VARCHAR2(100) NOT NULL,
    id_pais          INTEGER NOT NULL
);

ALTER TABLE tbl_usuarios ADD CONSTRAINT tbl_usuarios_pk PRIMARY KEY ( id_usuario );

ALTER TABLE tbl_podcasts
    ADD CONSTRAINT podcasts_tbl_idiomas_fk FOREIGN KEY ( id_idioma )
        REFERENCES tbl_idiomas ( id_idioma );

ALTER TABLE tbl_albumes
    ADD CONSTRAINT tbl_albumes_tbl_artistas_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_artistas ( id_usuario );

ALTER TABLE tbl_artistas
    ADD CONSTRAINT tbl_artistas_tbl_merch_fk FOREIGN KEY ( id_merch )
        REFERENCES tbl_merch ( id_merch );

ALTER TABLE tbl_artistas
    ADD CONSTRAINT tbl_artistas_tbl_usuarios_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_usuarios ( id_usuario );

ALTER TABLE tbl_canciones_artistas
    ADD CONSTRAINT tbl_can_art_tbl_canciones_fk FOREIGN KEY ( id_media )
        REFERENCES tbl_canciones ( id_media );

ALTER TABLE tbl_canciones
    ADD CONSTRAINT tbl_can_tbl_gen_musical_fk FOREIGN KEY ( id_genero_musical )
        REFERENCES tbl_generos_musicales ( id_genero_musical );

ALTER TABLE tbl_canciones_artistas
    ADD CONSTRAINT tbl_canc_tbl_art_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_artistas ( id_usuario );

ALTER TABLE tbl_canciones
    ADD CONSTRAINT tbl_canciones_tbl_albumes_fk FOREIGN KEY ( id_album )
        REFERENCES tbl_albumes ( id_album );

ALTER TABLE tbl_canciones
    ADD CONSTRAINT tbl_canciones_tbl_artistas_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_artistas ( id_usuario );

ALTER TABLE tbl_canciones
    ADD CONSTRAINT tbl_canciones_tbl_creditos_fk FOREIGN KEY ( id_creditos_musicales )
        REFERENCES tbl_creditos ( id_creditos_musicales );

ALTER TABLE tbl_canciones
    ADD CONSTRAINT tbl_canciones_tbl_idiomas_fk FOREIGN KEY ( id_idioma )
        REFERENCES tbl_idiomas ( id_idioma );

ALTER TABLE tbl_canciones
    ADD CONSTRAINT tbl_canciones_tbl_media_fk FOREIGN KEY ( id_media )
        REFERENCES tbl_media ( id_media );

ALTER TABLE tbl_creditos
    ADD CONSTRAINT tbl_credi_tbl_prod_fk FOREIGN KEY ( id_productor )
        REFERENCES tbl_productores ( id_productor );

ALTER TABLE tbl_creditos
    ADD CONSTRAINT tbl_creditos_tbl_artistas_fk FOREIGN KEY ( id_artista )
        REFERENCES tbl_artistas ( id_usuario );

ALTER TABLE tbl_episodio
    ADD CONSTRAINT tbl_episodio_podcasts_fk FOREIGN KEY ( id_podcast )
        REFERENCES tbl_podcasts ( id_podcast );

ALTER TABLE tbl_episodio
    ADD CONSTRAINT tbl_episodio_tbl_media_fk FOREIGN KEY ( id_media )
        REFERENCES tbl_media ( id_media );

ALTER TABLE tbl_eventos
    ADD CONSTRAINT tbl_eventos_tbl_artistas_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_artistas ( id_usuario );

ALTER TABLE tbl_eventos
    ADD CONSTRAINT tbl_eventos_tbl_lugares_fk FOREIGN KEY ( id_lugar )
        REFERENCES tbl_lugares ( id_lugar );

ALTER TABLE tbl_facturas
    ADD CONSTRAINT tbl_fact_tbl_usu_est_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_usuario_estandar ( id_usuario );

ALTER TABLE tbl_facturas
    ADD CONSTRAINT tbl_facturas_tbl_planes_fk FOREIGN KEY ( id_plan )
        REFERENCES tbl_planes ( id_plan );

ALTER TABLE tbl_historial_canciones
    ADD CONSTRAINT tbl_hist_canc_tbl_canc_fk FOREIGN KEY ( id_media )
        REFERENCES tbl_canciones ( id_media );

ALTER TABLE tbl_historial_canciones
    ADD CONSTRAINT tbl_hist_canc_tbl_hist_repr_fk FOREIGN KEY ( id_historial_de_reproduccion )
        REFERENCES tbl_historial_reproduccion ( id_historial_repr );

ALTER TABLE tbl_listas_seguidas
    ADD CONSTRAINT tbl_list_seg_tbl_list_repr_fk FOREIGN KEY ( id_lista_reproduccion )
        REFERENCES tbl_listas_reproduccion ( id_lista_reproduccion );

ALTER TABLE tbl_listas_reproduccion
    ADD CONSTRAINT tbl_listas_repr_tbl_usu_est_fk FOREIGN KEY ( id_usuario_propietario )
        REFERENCES tbl_usuario_estandar ( id_usuario );

ALTER TABLE tbl_listas_seguidas
    ADD CONSTRAINT tbl_listas_seg_tbl_rol_fk FOREIGN KEY ( id_rol )
        REFERENCES tbl_rol_lista_r ( id_rol );

ALTER TABLE tbl_listas_seguidas
    ADD CONSTRAINT tbl_listas_seg_tbl_usu_est_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_usuario_estandar ( id_usuario );

ALTER TABLE tbl_lugares
    ADD CONSTRAINT tbl_lugares_tbl_paises_fk FOREIGN KEY ( id_pais )
        REFERENCES tbl_paises ( id_pais );

ALTER TABLE tbl_merch
    ADD CONSTRAINT tbl_merch_tbl_tallas_fk FOREIGN KEY ( id_talla )
        REFERENCES tbl_tallas ( id_talla );

ALTER TABLE tbl_pago_planes
    ADD CONSTRAINT tbl_pago_plan_tbl_usu_est_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_usuario_estandar ( id_usuario );

ALTER TABLE tbl_pago_planes
    ADD CONSTRAINT tbl_pago_planes_tbl_planes_fk FOREIGN KEY ( id_plan )
        REFERENCES tbl_planes ( id_plan );

ALTER TABLE tbl_paises
    ADD CONSTRAINT tbl_paises_tbl_idiomas_fk FOREIGN KEY ( id_idioma )
        REFERENCES tbl_idiomas ( id_idioma );

ALTER TABLE tbl_podcasters
    ADD CONSTRAINT tbl_podcasters_tbl_podcasts_fk FOREIGN KEY ( id_podcast )
        REFERENCES tbl_podcasts ( id_podcast );

ALTER TABLE tbl_podcasters
    ADD CONSTRAINT tbl_podcasters_tbl_usuarios_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_usuarios ( id_usuario );

ALTER TABLE tbl_podcasts
    ADD CONSTRAINT tbl_podcasts_tbl_podcasters_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_podcasters ( id_usuario );

ALTER TABLE tbl_usuario_estandar
    ADD CONSTRAINT tbl_usu_est_tbl_hist_repr_fk FOREIGN KEY ( id_historial_de_reproduccion )
        REFERENCES tbl_historial_reproduccion ( id_historial_repr );

ALTER TABLE tbl_usuario_estandar
    ADD CONSTRAINT tbl_usu_est_tbl_pago_plan_fk FOREIGN KEY ( id_plan_pagado )
        REFERENCES tbl_pago_planes ( id_plan_pagado );

ALTER TABLE tbl_usuario_estandar
    ADD CONSTRAINT tbl_usu_est_tbl_plan_fk FOREIGN KEY ( id_plan )
        REFERENCES tbl_planes ( id_plan );

ALTER TABLE tbl_usuario_estandar
    ADD CONSTRAINT tbl_usu_est_tbl_usu_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_usuarios ( id_usuario );

ALTER TABLE tbl_usuario_red_social
    ADD CONSTRAINT tbl_usu_red_red_social_fk FOREIGN KEY ( id_red_social )
        REFERENCES tbl_tipo_redes_sociales ( id_red_social );

ALTER TABLE tbl_usuario_red_social
    ADD CONSTRAINT tbl_usu_red_social_tbl_art_fk FOREIGN KEY ( id_usuario )
        REFERENCES tbl_artistas ( id_usuario );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usuarios_tbl_genero_fk FOREIGN KEY ( id_genero )
        REFERENCES tbl_genero ( id_genero );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usuarios_tbl_paises_fk FOREIGN KEY ( id_pais )
        REFERENCES tbl_paises ( id_pais );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            33
-- CREATE INDEX                             3
-- ALTER TABLE                             76
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
