-- USER SQL
CREATE USER "C##SPT" IDENTIFIED BY "oracle"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "C##SPT" QUOTA UNLIMITED ON "SYSTEM";
ALTER USER "C##SPT" QUOTA UNLIMITED ON "SYSAUX";
ALTER USER "C##SPT" QUOTA UNLIMITED ON "USERS";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "C##SPT" ;
GRANT CREATE TRIGGER TO "C##SPT" ;
GRANT CREATE MATERIALIZED VIEW TO "C##SPT" ;
GRANT CREATE VIEW TO "C##SPT" ;
GRANT CREATE SESSION TO "C##SPT" ;
GRANT CREATE TABLE TO "C##SPT" ;
GRANT CREATE TYPE TO "C##SPT" ;
GRANT CREATE PUBLIC DATABASE LINK TO "C##SPT" ;
GRANT CREATE SEQUENCE TO "C##SPT" ;
GRANT CREATE PROCEDURE TO "C##SPT" ;

